app/app/core/urls.py
from django.urls import path
from app.core import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.home, name='home'),
    path('signin/', auth_views.LoginView.as_view(template_name='signin.html'), name='signin'),
    path('signup/', views.signup, name='signup'),
    path('logout/', auth_views.LogoutView.as_view(next_page='core:home'), name='logout'),
]

app/app/curriculos/urls.py
from django.urls import path
from app.curriculos import views

urlpatterns = [
    path('addCurriculo/', views.add, name='addCurriculo'),
]

app/app/pessoas/api/urls.py
from django.urls import path
from .views import list_all_users

urlpatterns = [
    path('list', list_all_users, name='list'),   
]

app/app/pessoas/urls.py
from django.urls import path, include

urlpatterns = [
    path('api/', include(('app.pessoas.api.urls', 'pessoa-api'), namespace='pessoa-api')),
]

app/app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


from django.contrib.auth.models import User
from rest_framework import routers, serializers, viewsets

# # Serializers define the API representation.
# class UserSerializer(serializers.HyperlinkedModelSerializer):
#     class Meta:
#         model = User
#         fields = ['url', 'username', 'email', 'is_staff']

# # ViewSets define the view behavior.
# class UserViewSet(viewsets.ModelViewSet):
#     queryset = User.objects.all()
#     serializer_class = UserSerializer

# # Routers provide an easy way of automatically determining the URL conf.
# router = routers.DefaultRouter()
# router.register(r'-users', UserViewSet)

urlpatterns = [
    path('',  include(('app.core.urls', 'core'),  namespace='core')),
    path('curriculo/',  include(('app.curriculos.urls', 'curriculos'),  namespace='curriculos')),
    path('vagas/', include(('app.vagas.urls', 'vagas'),  namespace='vagas')),
    path('pessoas/', include(('app.pessoas.urls', 'pessoas'),  namespace='pessoas')),

    path('admin/', admin.site.urls)
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

app/app/vagas/api/urls.py
from django.urls import path
from .views import list_all_vagas, add_new_vaga

urlpatterns = [
    path('list', list_all_vagas, name='list'),
    path('add', add_new_vaga, name='add'),
    
]

app/app/vagas/urls.py
from django.urls import path, include




urlpatterns = [
    path('api/', include(('app.vagas.api.urls', 'vaga-api'), namespace='vaga-api')),
]

app/app/core/models.py
from django.db import models

# Create your models here.

app/app/curriculos/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Curriculo(models.Model):
  user = models.ForeignKey(User, on_delete=models.CASCADE)

  url = models.FileField(("Curriculo"), upload_to='curriculos', max_length=100, blank=True)
  
  created_at = models.DateTimeField(("Criado em"), auto_now_add=True)
  updated_at = models.DateTimeField(("Atualizado em"), auto_now=True)


  def __str__(self):
      return str(self.user) + str(self.url)

  class Meta:
    verbose_name = 'Curriculo'
    verbose_name_plural = 'Curriculos'
    ordering=['user']

app/app/pessoas/models.py
from django.db import models

# Create your models here.

app/app/vagas/models.py
from django.db import models

# Create your models here.
class Vaga(models.Model):
  name = models.CharField(("Nome"), max_length=50)
  description = models.TextField(("Descrição"), blank=True)
  
  created_at = models.DateTimeField(("Criado em"), auto_now_add=True)
  updated_at = models.DateTimeField(("Atualizado em"), auto_now=True)

  def __str__(self):
    return self.name
  
  class Meta:
    verbose_name = 'Vaga'
    verbose_name_plural = 'Vagas'
    ordering=['name']

app/app/core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignUpForm(UserCreationForm):
  email = forms.EmailField(label='E-mail')


  def clean_email(self):
      email = self.cleaned_data["email"]

      if User.objects.filter(email=email).exists():
        raise forms.ValidationError('E-mail já cadastrado')
      
      return email
  


  def save(self, commit=True):
    user = super().save(commit=False)
    user.email = self.cleaned_data['email']
    
    if commit:
      user.save()
    
    return user

app/app/curriculos/forms.py
from django import forms
from django.db import models
from .models import Curriculo

class CurriculoCreateForm(forms.ModelForm):
  """
  A form that creates a user, with no privileges, from the given username and
  password.
  """
    
  def save(self, user):
    
    instance = super().save(commit=False)
    instance.user = user
    
    instance.save()

    return instance

  class Meta:
    model = Curriculo
    fields = ("url",)
  

app/app/core/views.py
import requests
import random
from django.shortcuts import render, redirect

from .forms import SignUpForm
from .filters import VagasFilter


# Create your views here.
def home(request):
  movies = []

  choice = random.choice([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
  api_response = requests.get(f'http://www.omdbapi.com/?apikey=f7bb1681&i=tt128501{choice}')
  movies.append(api_response.json()['Title'])

  choice = random.choice([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
  api_response = requests.get(f'http://www.omdbapi.com/?apikey=f7bb1681&i=tt12850{choice}8')
  movies.append(api_response.json()['Title'])
  
  

  return render(request, 'home.html', context= { 
    'movies': movies, 
    'filter': VagasFilter(request.GET)})


def signup(request):
  template_name = 'signup.html'
  
  if request.method == 'POST':
    form = SignUpForm(request.POST)
    if form.is_valid():
      form.save()
      return redirect('core:home')
  else:
    form = SignUpForm()

  context = {
    'form': form
  }
  return render(request, template_name, context)

app/app/curriculos/views.py
from django.shortcuts import render, redirect
from .forms import CurriculoCreateForm

# Create your views here.
def add(request):
  template_name = 'addCurriculo.html'
  
  if request.method == 'POST':
    form = CurriculoCreateForm(request.POST, request.FILES)
    
    if form.is_valid():
      form.save(user=request.user)
      return redirect('core:home')
  else:
    form = CurriculoCreateForm()

  context = {
    'form': form
  }
  return render(request, template_name, context)

app/app/pessoas/api/views.py
from rest_framework import status
from rest_framework.response import Response
from rest_framework.decorators import api_view, authentication_classes, permission_classes
from rest_framework.renderers import JSONRenderer

from django.contrib.auth.models import User
from .serializers import UserSerializer

@api_view(['GET'], )
@authentication_classes([])
@permission_classes([])
def list_all_users(request):
  if request.method == 'GET':
    try:
      users = User.objects.all()
      serializer = UserSerializer(users, many=True)
      
      return Response(serializer.data)
      
    except ValueError:
      return Response(status=status.HTTP_404_NOT_FOUND)

app/app/pessoas/views.py
from django.shortcuts import render

# Create your views here.

app/app/vagas/api/views.py
from rest_framework import status
from rest_framework.response import Response
from rest_framework.decorators import api_view, authentication_classes, permission_classes
from rest_framework.renderers import JSONRenderer

from app.vagas.models import Vaga
from .serializers import VagaSerializer

@api_view(['GET'], )
@authentication_classes([])
@permission_classes([])
def list_all_vagas(request):
  if request.method == 'GET':
    try:
      vagas = Vaga.objects.all()
      serializer = VagaSerializer(vagas, many=True)
      
      return Response(serializer.data)
      
    except ValueError:
      return Response(status=status.HTTP_404_NOT_FOUND)



@api_view(['POST'], )
@authentication_classes([])
@permission_classes([])
def add_new_vaga(request):
  if request.method == 'POST':
    print(request.data)
    serializer = VagaSerializer(data = request.data)

    if serializer.is_valid():
      serializer.save()
      return Response(serializer.data)

  

app/app/vagas/views.py
from django.shortcuts import render

# Create your views here.

app/app/core/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="Simple app - Cadastro de curriculos" />

    <title>Simple App</title>
    {% comment %}
    <link
      rel="stylesheet"
      href="http://yui.yahooapis.com/pure/0.3.0/pure-min.css"
    />
    {% endcomment %}
    <link rel="stylesheet" href="{% static 'css/base.css' %}" />
    <link rel="stylesheet" href="{% static 'css/home.css' %}" />
    <link rel="stylesheet" href="{% static 'css/signin.css' %}" />
    <link rel="stylesheet" href="{% static 'css/signup.css' %}" />
    <link rel="stylesheet" href="{% static 'css/curriculo.css' %}" />
  </head>
  <body>
    <header>
      {% if user.is_authenticated %}
      <h1>Bem vindo {{user.username}}</h1>
      {% else %}
      <a class="pure-menu-heading" href="{% url 'core:home'%}">SIMPLE APP</a>
      {% endif %}

      <ul>
        <li>
          <a href="{% url 'core:home'%}">Início</a>
        </li>

        {% if user.is_authenticated %}
        <li>
          <a href="{% url 'curriculos:addCurriculo'%}">Adicionar Curriculo</a>
        </li>
        <li><a href="{% url 'core:logout'%}">Sair</a></li>
        {% else %}
        <li>
          <a href="{% url 'core:signup'%}">Cadastrar</a>
        </li>
        <li><a href="{% url 'core:signin'%}">Entrar</a></li>
        {% endif %}
      </ul>
    </header>

    {% block content %}{% endblock %}
    <footer>Simple MOOC - Uma simples plataforma de ensino a distância</footer>
  </body>
</html>

app/app/core/templates/home.html
{% extends "base.html" %} 


{% block content %}



<div class="home_main_container">
  <form method="get" class='filter'>
    {{ filter.form  }}
    <button type="submit">Procurar</button>
  </form>

  <table class="table">
    <th>
      <tr>
        <td class="thead">Vaga</td>
        <td class="thead">Descrição</td>
        <td class="thead">Ultima atualização</td>
        <td class="thead">Filme</td>
      </tr>
    </th>
    
    {% for field  in filter.qs %}
    <tb>
      <tr>
        <td class='tbody'>{{field.name}}</td>
        <td class='tbody'>{{field.description}}</td>
        <td class='tbody'>{{field.updated_at}}</td>
        <td class='tbody'>{{movies | random }}</td>
      </tr>
    </tb>
    {% endfor %}
  
  </table>
</div>

{% endblock %}

app/app/core/templates/signin.html
{% extends "base.html" %} {% block content %} {% if form.errors %}
<p>{{ form.errors }}</p>
<p>Please try again.</p>
{% endif %} {% if next %} {% if user.is_authenticated %}
<p>
  Your account doesn't have access to this page. To proceed, please login with
  an account that has access.
</p>
{% else %}
<p>Please login to see this page.</p>
{% endif %} {% endif %}

<form class="signin_main_containeir" method="post">
  {% csrf_token %}
  <table>
    {% for field in form %}
    <tr>
      <td>{{ field.label_tag }}</td>
      <td>{{ field }}</td>
    </tr>
    {% endfor %}
  </table>

  <input type="submit" value="Entrar" />
  <input type="hidden" name="next" value="{{ next }}" />
</form>

{# Assumes you setup the password_reset view in your URLconf #}
<p><a href="{% url 'core:home' %}">Lost password?</a></p>

{% endblock %}

app/app/core/templates/signup.html
{% extends "base.html" %} {% block content %} {% if form.errors %}
<p>{{ form.errors }}</p>
<p>Please try again.</p>
{% endif %} {% if next %} {% if user.is_authenticated %}
<p>
  Your account doesn't have access to this page. To proceed, please login with
  an account that has access.
</p>
{% else %}
<p>Please login to see this page.</p>
{% endif %} {% endif %}

<form class="signup_main_containeir" method="post">
  {% csrf_token %}
  <table>
    {% for field in form %}
    <tr>
      <td>{{ field.label_tag }}</td>
      <td>{{ field }}</td>
    </tr>
    {% endfor %}
  </table>

  <input type="submit" value="Cadastrar" />
  <input type="hidden" name="next" value="{{ next }}" />
</form>

{# Assumes you setup the password_reset view in your URLconf #}
<p><a href="{% url 'core:home' %}">Lost password?</a></p>

{% endblock %}

app/app/curriculos/templates/addCurriculo.html
{% extends "base.html" %} {% block content %} {% if form.errors %}
<p>{{ form.errors }}</p>
<p>Please try again.</p>
{% endif %} {% if next %} {% if user.is_authenticated %}
<p>
  Your account doesn't have access to this page. To proceed, please login with
  an account that has access.
</p>
{% else %}
<p>Please login to see this page.</p>
{% endif %} {% endif %}

<form
  class="curriculo_main_containeir"
  method="post"
  enctype="multipart/form-data"
>
  {% csrf_token %}
  <h3>Adicione seu curriculo</h3>
  <div>{% for field in form %} {{ field }} {% endfor %}</div>

  <input type="submit" value="Add" />
  <input type="hidden" name="next" value="{{ next }}" />
</form>

{% endblock %}